spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A Magic 8 Ball App"
name = "magic-eight-ball-typescript"
version = "0.1.0"

[[trigger.http]]
route = "/magic-8"
component = "magic-eight-ball-typescript"

[component.magic-eight-ball-typescript]
source = "target/magic-eight-ball-typescript.wasm"
exclude_files = ["**/node_modules"]
[component.magic-eight-ball-typescript.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]
