apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-typescript
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-typescript
  template:
    metadata:
      labels:
        app: hello-typescript
    spec:
      runtimeClassName: wasmtime-spin
      containers:
        - name: hello-typescript
          image: ghcr.io/kate-goldenring/hello-typescript:0.1.0
          command: ["/"]
---
apiVersion: v1
kind: Service
metadata:
  name: hello-typescript
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: hello-typescript
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-typescript
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          - path: /hello-typescript
            pathType: Prefix
            backend:
              service:
                name: hello-typescript
                port:
                  number: 80
