apiVersion: apps/v1
kind: Deployment
metadata:
  name: magic-8-ball-ts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: magic-8-ball-ts
  template:
    metadata:
      labels:
        app: magic-8-ball-ts
    spec:
      runtimeClassName: wasmtime-spin
      containers:
        - name: magic-8-ball-ts
          image: ghcr.io/kate-goldenring/magic-8-ball-ts:0.1.0
          command: ["/"]
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: magic-8-ball-ts
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: magic-8-ball-ts
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: magic-8-ball-ts
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: magic-8-ball-ts
                port:
                  number: 80
