spin_manifest_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A Magic 8 Ball"
name = "magic-8-ball-ts"
trigger = { type = "http", base = "/" }
version = "0.1.0"


[[component]]
source = "spin_static_fs.wasm"
id = "fileserver"
files = [ { source = "frontend/", destination = "/" } ]
[component.trigger]
route = "/..."

[[component]]
id = "magic-8-ball"
source = "target/spin-http-js.wasm"
exclude_files = ["**/node_modules"]
[component.trigger]
route = "/magic-8"
[component.build]
command = "npm run build"
