spin_manifest_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "Spin the Wheel!"
name = "lottery"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "lottery"
source = "target/wasm32-wasi/release/lottery.wasm"
allowed_http_hosts = []
sqlite_databases = ["default"]
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
