spin_manifest_version = 2

[application]
authors = ["Mikkel Mørk Hegnhøj <mikkel@fermyon.com>"]
description = ""
name = "my_application"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "my-application"

[component.my-application]
source = "target/my-application.wasm"
exclude_files = ["**/node_modules"]
[component.my-application.build]
command = "npm run build"
