spin_manifest_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = ""
name = "magic-8-ball"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.3/spin_static_fs.wasm", digest = "sha256:38bf971900228222f7f6b2ccee5051f399adca58d71692cdfdea98997965fd0d" }
id = "fileserver"
files = [ { source = "../../frontend/", destination = "/" } ]
[component.trigger]
route = "/..."

[[component]]
# Be sure to set the username, password, and replace `my-redis-instance` for your Redis DB
environment = { REDIS_ADDRESS = "redis://username:password@my-redis-instance.cloud.redislabs.com:1234" }
id = "magic-8-ball"
source = "target/wasm32-wasi/release/magic_8_ball.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/magic-8"
[component.build]
command = "cargo build --target wasm32-wasi --release"
