spin_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = ""
name = "magic-8-ball"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
source = "spin_static_fs.wasm"
id = "fileserver"
# Be sure to copy the frontend files to this directory
files = [ { source = "frontend/", destination = "/" } ]
[component.trigger]
route = "/..."

[[component]]
id = "magic-8-ball"
source = "target/wasm32-wasi/release/magic_8_ball.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/magic-8"
[component.build]
command = "cargo build --target wasm32-wasi --release"