apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-rust
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-rust
  template:
    metadata:
      labels:
        app: hello-rust
    spec:
      runtimeClassName: wasmtime-spin
      containers:
        - name: hello-rust
          image: ghcr.io/kate-goldenring/hello-rust:0.1.0
          command: ["/"]
---
apiVersion: v1
kind: Service
metadata:
  name: hello-rust
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: hello-rust
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-rust
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          - path: /hello-rust
            pathType: Prefix
            backend:
              service:
                name: hello-rust
                port:
                  number: 80
